### ISSUE TITLE
[Customização] Maior suporte para Customização do UI padrão do TextField

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [SwitchDreams/switch-ui#136]
O componente TextField no projeto praora ficou um pouco diferente do nosso padrão e para isso precisamos de maiores customizações como:
- Cor do texto de suporte

**Comment by griseduardo** [comment]
Olá, eu gostaria de trabalhar nessa issue, pode atribuir para mim?

**Comment by PedroAugustoRamalhoDuarte** [comment]
Claro @griseduardo, muito obrigado!

**Comment by griseduardo** [comment]
@PedroAugustoRamalhoDuarte bom dia, abri o PR da issue aqui: https://github.com/SwitchDreams/switch-ui/pull/140

**Comment by PedroAugustoRamalhoDuarte** [comment]
Mandei a revisão lá @griseduardo, valeu!!
